const WORDS={stringent:["/ˈstrɪndʒənt/","严格的；严厉的","IELTS 7+"],mitigate:["/ˈmɪtɪɡeɪt/","缓解；减轻","IELTS 7+"],degradation:["/ˌdeɡrəˈdeɪʃən/","退化；恶化","IELTS 7+"],implement:["/ˈɪmplɪment/","实施；执行","IELTS 6+"],significant:["/sɪɡˈnɪfɪkənt/","重要的；显著的","IELTS 6+"],substantial:["/səbˈstænʃəl/","大量的；重大的","IELTS 7+"],consequently:["/ˈkɒnsɪkwentli/","因此；所以","IELTS 7+"],facilitate:["/fəˈsɪlɪteɪt/","促进；使便利","IELTS 7+"],considerable:["/kənˈsɪdərəbəl/","相当大的","IELTS 6+"],controversial:["/ˌkɒntrəˈvɜːʃəl/","有争议的","IELTS 7+"],conventional:["/kənˈvenʃənəl/","传统的；惯例的","IELTS 6+"],acquire:["/əˈkwaɪə/","获得；习得","IELTS 6+"],evident:["/ˈevɪdənt/","明显的","IELTS 6+"],inevitable:["/ɪnˈevɪtəbəl/","不可避免的","IELTS 7+"],predominant:["/prɪˈdɒmɪnənt/","占主导地位的","IELTS 8+"]};
let book=null,rendition=null,currentWord=null,locations=null;
const $=id=>document.getElementById(id);
$("epubInput").onchange=e=>{if(e.target.files[0])openBook(e.target.files[0])};
$("prev").onclick=()=>rendition?.prev();$("next").onclick=()=>rendition?.next();
$("fontUp").onclick=()=>rendition?.themes.fontSize("115%");$("fontDown").onclick=()=>rendition?.themes.fontSize("90%");
$("theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("reader-dark",document.body.classList.contains("dark"))};
if(localStorage.getItem("reader-dark")==="true")document.body.classList.add("dark");
async function openBook(file){try{
const url=URL.createObjectURL(file);book=ePub(url);rendition=book.renderTo("viewer",{width:"100%",height:"100%",spread:"none"});
rendition.themes.default({body:{color:"inherit !important",background:"transparent !important",fontFamily:"Georgia,serif",lineHeight:"1.75",padding:"0 8% !important"},".reader-vocab":{background:"rgba(255,230,90,.55)",borderRadius:"3px",cursor:"pointer"}});
rendition.on("rendered",(_s,v)=>{try{highlight(v.document)}catch(e){console.warn(e)}});
rendition.on("relocated",loc=>{if(loc?.start){localStorage.setItem("reader-cfi",loc.start.cfi);updateProgress(loc)}});
const meta=await book.loaded.metadata;$("bookTitle").textContent=meta.title||file.name.replace(/\.epub$/i,"");$("bookAuthor").textContent=meta.creator||"EPUB";
await toc();const saved=localStorage.getItem("reader-cfi");await rendition.display(saved||undefined);$("prev").disabled=false;$("next").disabled=false;toast("EPUB loaded successfully");
}catch(e){console.error(e);toast("This EPUB could not be opened. Please try another EPUB.")}}
async function toc(){const nav=await book.loaded.navigation;$("toc").innerHTML="";const walk=arr=>arr.forEach(x=>{if(x.label&&x.href){const b=document.createElement("button");b.textContent=x.label.trim();b.onclick=()=>rendition.display(x.href);$("toc").appendChild(b)}if(x.subitems)walk(x.subitems)});walk(nav.toc||[]);if(!$("toc").children.length)$("toc").innerHTML='<small class="muted">No table of contents found.</small>'}
function highlight(doc){if(!doc?.body)return;const keys=Object.keys(WORDS).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|");const re=new RegExp("\\b("+keys+")\\b","gi");const walker=doc.createTreeWalker(doc.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(!n.nodeValue.trim()||n.parentElement.closest(".reader-vocab,script,style")||!re.test(n.nodeValue))return;re.lastIndex=0;const f=doc.createDocumentFragment();let last=0,m;while(m=re.exec(n.nodeValue)){f.appendChild(doc.createTextNode(n.nodeValue.slice(last,m.index)));const s=doc.createElement("span");s.className="reader-vocab";s.textContent=m[0];s.onclick=()=>showWord(m[0].toLowerCase());f.appendChild(s);last=m.index+m[0].length}f.appendChild(doc.createTextNode(n.nodeValue.slice(last)));n.parentNode.replaceChild(f,n)})}
function showWord(w){const d=WORDS[w];if(!d)return;currentWord=w;$("word").textContent=w;$("pron").textContent=d[0];$("meaning").textContent=d[1];$("level").textContent=d[2];$("popup").classList.remove("hidden")}
$("close").onclick=()=>$("popup").classList.add("hidden");$("save").onclick=()=>{let a=JSON.parse(localStorage.getItem("reader-vocab")||"[]");if(currentWord&&!a.includes(currentWord))a.push(currentWord);localStorage.setItem("reader-vocab",JSON.stringify(a));$("popup").classList.add("hidden");toast(currentWord+" added to vocabulary")};
function updateProgress(loc){try{if(!locations){book.locations.generate(1600).then(l=>{locations=l;updateProgress(loc)})}else{const p=Math.round(locations.percentageFromCfi(loc.start.cfi)*100);$("progress").textContent=p+"%";$("progressFill").style.width=p+"%";$("location").textContent=p+"%"}}catch(e){}}
function toast(m){$("toast").textContent=m;$("toast").classList.remove("hidden");clearTimeout(window.t);window.t=setTimeout(()=>$("toast").classList.add("hidden"),1800)}